### ISSUE TITLE
Network Error [ FIXED ]

### ISSUE THREAD

**Issue by binskyi** [SomnathDas/DoujinCodeToPdf#3]
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read',
  response: undefined
}

**Comment by SomnathDas** [comment]
@Bintang73 I've just tested it and it's working. Your error occurred due to Network instability.
Thank you and have a great day!
